fix:  audit module doesn't support strict_ssl flag
verdaccio/verdaccio-audit pull request #12
Opened 2019-07-28 14:25 UTC by dfrencham

Add support for strict_ssl as discussed in [1293](https://github.com/verdaccio/verdaccio/issues/1293)

2019-07-28 19:09 UTC, juanpicado requested changes
Thanks so much ! It is almost perfect, but could you update the docs https://github.com/verdaccio/verdaccio-audit#usage ? otherwise nobody will realize.

2019-07-28 22:33 UTC, dfrencham commented
> Thanks so much ! It is almost perfect, but could you update the docs https://github.com/verdaccio/verdaccio-audit#usage ? otherwise nobody will realize.

No worries mate, I have updated the docs in commit f7d3f86 

Oh and, you're welcome! cheers for all your hard work.

2019-07-29 07:57 UTC, juanpicado approved these changes

2019-07-29 07:58 UTC, merged

2019-07-29 07:58 UTC, juanpicado commented
Thanks @dfrencham , it will be shipped this week.